Quick and dirty migration to 2.11.0-M7
15 compile errors found:

```
[error] /Users/adriaan/git/akka-all/akka/akka-channels/src/main/scala/akka/channels/ChannelRef.scala:35: macro implementation has wrong shape:
[error]  required: (c: scala.reflect.macros.WhiteboxContext)(msg: c.Expr[M]): c.Expr[scala.concurrent.Future[_$1]] forSome { type _$1 }
[error]  or      : (c: scala.reflect.macros.WhiteboxContext)(msg: c.Tree): c.Tree[]
[error]  found   : (c: reflect.macros.Context{type PrefixType = akka.channels.ChannelRef[Channel]})(msg: c.Expr[Msg]): c.Expr[scala.concurrent.Future[_]]
[error] type mismatch for return type: c.Expr[scala.concurrent.Future[_]] does not conform to c.Expr[scala.concurrent.Future[_$1]] forSome { type _$1 }
[error]   def <-?-[M](msg: M): Future[_] = macro macros.Ask.impl[ChannelList, Any, Any, T, M]
[error]       ^
[error] /Users/adriaan/git/akka-all/akka/akka-channels/src/main/scala/akka/channels/Ops.scala:58: macro implementation has wrong shape:
[error]  required: (c: scala.reflect.macros.WhiteboxContext)(channel: c.Expr[akka.channels.ChannelRef[C]]): c.Expr[scala.concurrent.Future[_$3]] forSome { type _$3 }
[error]  or      : (c: scala.reflect.macros.WhiteboxContext)(channel: c.Tree): c.Tree[]
[error]  found   : (c: reflect.macros.Context{type PrefixType = akka.channels.FutureOps[Msg]})(channel: c.Expr[akka.channels.ChannelRef[Channel]]): c.Expr[scala.concurrent.Future[_]]
[error] type mismatch for return type: c.Expr[scala.concurrent.Future[_]] does not conform to c.Expr[scala.concurrent.Future[_$3]] forSome { type _$3 }
[error]   def -?->[C <: ChannelList](channel: ChannelRef[C]): Future[_] = macro macros.Ask.futureImpl[ChannelList, Any, C, T]
[error]       ^
[error] /Users/adriaan/git/akka-all/akka/akka-channels/src/main/scala/akka/channels/Ops.scala:68: macro implementation has wrong shape:
[error]  required: (c: scala.reflect.macros.WhiteboxContext)(channel: c.Expr[akka.channels.ChannelRef[C]]): c.Expr[scala.concurrent.Future[_$5]] forSome { type _$5 }
[error]  or      : (c: scala.reflect.macros.WhiteboxContext)(channel: c.Tree): c.Tree[]
[error]  found   : (c: reflect.macros.Context{type PrefixType = akka.channels.AnyOps[Msg]})(channel: c.Expr[akka.channels.ChannelRef[Channel]]): c.Expr[scala.concurrent.Future[_]]
[error] type mismatch for return type: c.Expr[scala.concurrent.Future[_]] does not conform to c.Expr[scala.concurrent.Future[_$5]] forSome { type _$5 }
[error]   def -?->[C <: ChannelList](channel: ChannelRef[C]): Future[_] = macro macros.Ask.opsImpl[ChannelList, Any, C, T]
[error]       ^
[error] three errors found
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:181: type mismatch;
[error]  found   : Long
[error]  required: scala.concurrent.duration.FiniteDuration
[error]         poller.poll(pollLength)
[error]                     ^
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:79: type mismatch;
[error]  found   : Long
[error]  required: Int
[error]     case Linger(value)               ? socket.setLinger(value)
[error]                                                         ^
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:80: type mismatch;
[error]  found   : Long
[error]  required: Int
[error]     case ReconnectIVL(value)         ? socket.setReconnectIVL(value)
[error]                                                               ^
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:81: type mismatch;
[error]  found   : Long
[error]  required: Int
[error]     case Backlog(value)              ? socket.setBacklog(value)
[error]                                                          ^
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:82: type mismatch;
[error]  found   : Long
[error]  required: Int
[error]     case ReconnectIVLMax(value)      ? socket.setReconnectIVLMax(value)
[error]                                                                  ^
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:84: type mismatch;
[error]  found   : Long
[error]  required: Int
[error]     case SendHighWatermark(value)    ? socket.setSndHWM(value)
[error]                                                         ^
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:85: type mismatch;
[error]  found   : Long
[error]  required: Int
[error]     case ReceiveHighWatermark(value) ? socket.setRcvHWM(value)
[error]                                                         ^
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:123: not found: value Poller
[error]     poller.register(socket, Poller.POLLIN)
[error]                             ^
[error] /Users/adriaan/git/akka-all/akka/akka-zeromq/src/main/scala/akka/zeromq/ConcurrentSocketActor.scala:203: type mismatch;
[error]  found   : Int(0)
[error]  required: scala.concurrent.duration.FiniteDuration
[error]     if (mode == PollCareful && (poller.poll(0) <= 0)) {
[error]                                             ^
[error] 9 errors found
[error] /Users/adriaan/git/akka-all/akka/akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala:58: pattern type is incompatible with expected type;
[error]  found   : akka.remote.testconductor.ClientFSM.Connecting.type
[error]  required: S
[error]         case Transition(_, Connecting, AwaitDone) ? // step 1, not there yet
[error]                            ^
[error] /Users/adriaan/git/akka-all/akka/akka-multi-node-testkit/src/main/scala/akka/remote/testkit/MultiNodeSpec.scala:267: value await is not a member of scala.concurrent.Future[Iterable[akka.remote.testconductor.RoleName]]
[error]  Note: implicit method awaitHelper is not applicable here because it comes after the application point and it lacks an explicit result type
[error]           testConductor.getNodes.await.filterNot(_ == myself).isEmpty
[error]                                  ^
[error] /Users/adriaan/git/akka-all/akka/akka-multi-node-testkit/src/main/scala/akka/remote/testkit/MultiNodeSpec.scala:354: value await is not a member of scala.concurrent.Future[akka.actor.Address]
[error]  Note: implicit method awaitHelper is not applicable here because it comes after the application point and it lacks an explicit result type
[error]   def node(role: RoleName): ActorPath = RootActorPath(testConductor.getAddressFor(role).await)
[error]                                                                                         ^
[error] three errors found
[error] (akka-zeromq/compile:compile) Compilation failed
[error] (akka-multi-node-testkit/compile:compile) Compilation failed
[error] (akka-channels-experimental/compile:compile) Compilation failed
[error] Total time: 95 s, completed Nov 22, 2013 11:20:01 AM
```